guest/blog/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("",views.blogindex,name="blog"),
    path("<int:blogid>/details",views.blogdetails,name="blogdetails"),
    path("<category>",views.category,name="category"),
]

guest/guestbook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('guest/', include('guest.urls')),
    path('todo_list/',include('todo_list.urls')),
    path('tasks/',include('tasks.urls')),
    path('projects/',include('projects.urls')),
    path('blog/',include('blog.urls')),
    path('project/',include('project.urls')),
]
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

guest/project/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("",views.IndexView.as_view(),name="index"),
    path("company/create",views.createCompany.as_view(),name="company"),
    path("<str:slug>",views.companyDetails.as_view(),name="details"),
    path("<str:slug>/update",views.companyUpdate.as_view(),name="edit"),
    path("<str:slug>/delete",views.companyDelete.as_view(),name="delete"),
    path("search/company",views.search,name="search"),

    path("languages/available",views.languages.as_view(),name="languages"),
    path("languages/create",views.createLang.as_view(),name="language"),
    path("language/<str:slug>/edit",views.UpdateLang.as_view(),name="editLang"),
    path("language/<str:slug>/delete",views.deleteLang.as_view(),name="deleteLang"),

    path("programmers/available",views.programmer.as_view(),name="programmers"),
    path("programmers/create",views.add.as_view(),name="add")
]

guest/projects/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("",views.index,name="index"),
    path("<int:id>",views.details,name="details"),
]

guest/project/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=50)
    location =models.CharField(max_length=100)
    created_on =models.DateTimeField(auto_now_add=True)
    image = models.FileField()
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse("index")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=50)
    created_on =models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(
        unique=True,
        editable=False,
        max_length=100
    )

    def get_absolute_url(self):
        return reverse("languages")

    def save(self,*args,**kwargs):
        value = self.name
        self.slug = slugify(value,allow_unicode=True)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name

class Programmer(models.Model):
    name = models.CharField(max_length=50)
    age =models.IntegerField()
    company =models.ForeignKey(Company,on_delete=models.CASCADE)
    language =models.ManyToManyField(Language,related_name="language")
    created_on =models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(
        unique=True,
        max_length=50,
        editable=False
        )

    def get_absolute_url(self):
        return reverse("index")

    def save(self,*args,**kwargs):
        value = self.name
        self.slug = slugify(value,allow_unicode=True)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name                    

guest/projects/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    technology = models.CharField(max_length=250)
    image = models.FileField()

    def __str__(self):
        return self.title

guest/project/views.py
from django.shortcuts import render
from django.views import generic
from .models import Company,Language,Programmer
from django.urls import reverse_lazy
from django.db.models import Q

# Create your views here.
class IndexView(generic.ListView):
    template_name ="project/index.html"
    context_object_name ="company"

    def get_queryset(self):
        return Company.objects.all()        

class createCompany(generic.CreateView):
    model = Company
    fields =["name","location","image","slug"]

class companyDetails(generic.DetailView):
    model = Company
    context_object_name ="companys"
    template_name ="project/details.html"

class companyUpdate(generic.UpdateView):
    model = Company
    fields =["name","location","image","slug"]

class companyDelete(generic.DeleteView):
    model = Company
    success_url = reverse_lazy("index")    

def search(request):
    q = request.GET.get('search' or None)

    if q is not None:
        search = Company.objects.filter(Q(name__contains = q)| Q(location__contains = q))
        context ={"company":search,"q":q}
        return render(request,"project/search.html",context)

class languages(generic.ListView):
    template_name ="project/languages.html"
    context_object_name ="lang"

    def get_queryset(self):
        return Language.objects.all()        

class createLang(generic.CreateView):
    model = Language
    fields =["name"]    

class UpdateLang(generic.UpdateView):
    model = Language
    fields =["name"]          

class deleteLang(generic.DeleteView):
    model = Language
    success_url= reverse_lazy("languages")

class programmer(generic.ListView):
    template_name ="programmers.html"
    context_object_name="programmers"

    def get_queryset(self):
        return Programmer.objects.all()   

class add(generic.CreateView):
    model = Programmer
    fields ='__all__'       

guest/projects/views.py
from django.shortcuts import render
from . models import Project
# Create your views here.
def index(request):
    projects = Project.objects.all()
    template_name = "projects/index.html"
    context ={"projects" : projects}
    return render(request,template_name,context)

def details(request,id):
    project = Project.objects.get(pk=id)
    template_name = "projects/details.html"
    context ={"project" : project}
    return render(request,template_name,context)    

guest/project/templates/project/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="shortcut icon" href="{%  static 'project/images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{%  static 'project/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%  static 'project/css/style.css' %}">
    <link rel="stylesheet" href="{%  static 'project/css/fontawesome-all.css' %}">
    <script src="{% static 'project/js/jquery.min.js' %}"></script>
    <script src="{% static 'project/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">
                TREE CAVE
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'languages' %}">Languages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'programmers' %}">Programmers</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <form action="{% url 'search' %}" method="GET">
                        <input type="text" class="form-control" placeholder="search" name="search">
                    </form>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

guest/project/templates/project/company_form.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
           <div class="col-md-8">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'project/template-form.html' %}
                <button type="submit" class="btn btn-block w-100 btn-dark">save company</button>
            </form>
           </div>
        </div>
    </div>
{% endblock %}

guest/project/templates/project/details.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
                <div class="col-md-8">
                    <img src="{{ companys.image.url }}" alt="{{ companys.name }}" class="w-100">
                </div>
                <div class="col-md-4">
                    <h5 class="mt-2">company</h5>
                    <p>{{ companys.name }}</p>
                    <h5 class="mt-2">Country</h5>
                    <p>{{ companys.location }}</p>
                    <div class="row">
                        <div class="col-md-6">
                            <a href="{% url 'edit' companys.slug %}" class="btn btn-primary btn-sm btn-block w-100">Edit {{ companys.name }}</a>
                        </div>
                        <div class="col-md-6">
                            <form action="{% url 'delete' companys.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="slug" value="{{ companys.slug }}">
                                <button type="submit" class="btn btn-danger btn-sm btn-block w-100">Delete {{ companys.name }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

guest/project/templates/project/index.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
           {% for companys in company %}
                <div class="col-md-3 mb-3">
                    <img src="{{ companys.image.url }}" alt="{{ companys.name }}" class="w-100">
                    <h5 class="mt-2">{{ companys.name }}</h5>
                    <p>{{ companys.location }}</p>
                    <a href="{% url 'details' companys.slug %}" class="btn btn-sm btn-block w-50 btn-dark">view details</a>
                </div>
           {% endfor %}
        </div>
        <div class="row float-right mt-5">
            <div class="mb-5">
                <a href="{% url 'company' %}" class="btn btn-sm btn-block w-100 btn-outline-secondary">Add company</a>
            </div>
        </div>
    </div>
{% endblock %}

guest/project/templates/project/language_form.html
{% extends 'project/base.html' %}
{%  block title %}
    Tree cave | New Language
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
       <div class="col-md-8">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'project/template-form.html' %}
            <button type="submit" class="btn btn-block w-100 btn-dark">save language</button>
        </form>
       </div>
    </div>
</div>
{% endblock %}

guest/project/templates/project/languages.html
{% extends 'project/base.html' %}
{%  block title %}
    Tree cave | Languages
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
       <div class="col-md-8">
        {% if lang %}
            <table class="table">
                <tbody>
                {% for l in lang %}
                    <tr>
                        <td>{{ l.name }}</td>
                        <td><a href="{% url 'editLang' l.slug %}"><span class="fa fa-pencil-alt text-dark"></span></a></td>
                        <td><a href="{% url 'deleteLang' l.slug %}"><span class="fa fa-trash text-dark"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
       </div>
    </div>
    <div class="row float-right mt-5">
        <div class="mb-5">
            <a href="{% url 'language' %}" class="btn btn-sm btn-block w-100 btn-outline-secondary">Add language</a>
        </div>
    </div>
</div>
{% endblock %}

guest/project/templates/project/programmer_form.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
           <div class="col-md-8">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'project/template-form.html' %}
                <button type="submit" class="btn btn-block w-100 btn-dark">save programmer</button>
            </form>
           </div>
        </div>
    </div>
{% endblock %}

guest/project/templates/project/programmer_list.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            {% for companys in programmers %}
            {% for company in companys.id.company_set.all %}
                <p>{{ company.name }}</p>
                <div class="col-md-8">
                    <img src="{{ companys.image.url }}" alt="{{ companys.name }}" class="w-100">
                </div>
                <div class="col-md-4">
                    <h5 class="mt-2">company</h5>
                    <p>{{ company.name }}</p>
                    <h5 class="mt-2">Country</h5>
                    <p>{{ companys.location }}</p>
                    <div class="row">
                        <div class="col-md-6">
                            <a href="{% url 'edit' companys.slug %}" class="btn btn-primary btn-sm btn-block w-100">Edit {{ companys.name }}</a>
                        </div>
                        <div class="col-md-6">
                            <form action="{% url 'delete' companys.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="slug" value="{{ companys.slug }}">
                                <button type="submit" class="btn btn-danger btn-sm btn-block w-100">Delete {{ companys.name }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endfor %}
            </div>
        </div>
    {% endblock %}

guest/project/templates/project/search.html
{% extends 'project/base.html' %}

{% block title %}
    Tree cave | search
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h5 class="mb-4">search resuts for: {{ q }}</h5>
        <div class="row">
        {% if company %}
           {% for companys in company %}
            <div class="col-md-3 mb-3">
               <img src="{{ companys.image.url }}" alt="{{ companys.name }}" class="w-100">
               <h5 class="mt-2">{{ companys.name }}</h5>
               <p>{{ companys.location }}</p>
               <a href="{% url 'details' companys.slug %}" class="btn btn-sm btn-block w-50 btn-dark">view details</a>
           </div>
            {% endfor %}
           {% else %}
            <div class="alert alert-danger col-md-12">There are no search results for: <strong>{{ q }}</strong></div>
           {% endif %}
        </div>
{% endblock %}

guest/project/templates/project/template-form.html
{% for field in form %}
<div class="form-group">
    <label for="name">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
</div>
{% endfor %}